[package]
name = "mass-pac"
version = "0.1.0"
edition = "2024"
authors = ["Nick Massey <nickmass@nickmass.com>"]
license = "MIT"

[dependencies]
blip_buf = "0.1.5"
direct_ring_buffer = "0.2"
glium = { git = "https://github.com/glium/glium.git", rev = "7c541983dcc5c1d516225559129ac9a27e9af4e8", features = [
    "simple_window_builder",
] }
pipewire = "0.8.0"
winit = "0.30.5"
zip = "7.2.0"
